name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start the traefik container
        run: |
          set -x
          docker network create public-network
          docker-compose pull

          LOG_LEVEL=debug \
            docker-compose up -d

          sleep 2
          docker ps

          curl -s 127.0.0.1:58888/api/http/routers | jq -r '.[] | .service' | sort

      - name: Show logs
        if: ${{ always() }}  # run this step regardless of the tests failing or passing
        run: |
          set -x
          docker ps
          docker logs traefik
